# Generated by Django 6.0.8 on 2026-10-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone'),
    ]

    def mark_existing_superusers_as_platform_owners(apps, schema_editor):
        User = apps.get_model('accounts', 'User')
        User.objects.using(schema_editor.connection.alias).filter(
            is_superuser=True,
        ).update(is_platform_owner=True)

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_superusers_as_platform_owners,
            migrations.RunPython.noop,
        ),
    ]
