# Generated by Django 6.0.8 on 2026-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_platform_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_platform_owner',
            field=models.BooleanField(default=False, help_text='Grants access to cross-company platform administration.', verbose_name='Platform owner'),
        ),
    ]
