# Generated by Django 6.0.8 on 2026-10-02 16:01

from django.db import migrations, models


def mark_existing_active_users_verified(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(is_active=True).update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_is_platform_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            mark_existing_active_users_verified,
            migrations.RunPython.noop,
        ),
    ]
