# Generated by Django 6.0.8 on 2026-10-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='business_type',
            field=models.CharField(choices=[('company', 'Company'), ('restaurant', 'Restaurant')], default='company', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='country_code',
            field=models.CharField(choices=[('EG', 'Egypt'), ('SA', 'Saudi Arabia')], default='EG', max_length=2),
        ),
    ]
