# Generated by Django 6.0.8 on 2026-09-26 16:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('sku', models.CharField(blank=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('unit', models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('m', 'Meter'), ('box', 'Box'), ('service', 'Service')], default='piece', max_length=16)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organizations.organization')),
            ],
            options={
                'ordering': ('name', 'id'),
                'indexes': [models.Index(fields=['organization', 'name'], name='product_org_name_idx'), models.Index(fields=['organization', 'is_active'], name='product_org_active_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='product_sale_price_nonnegative'), models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='product_cost_price_nonnegative'), models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('organization', 'sku'), name='unique_product_sku_per_organization')],
            },
        ),
    ]
