# Generated by Django 6.0.8 on 2026-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    def populate_actor_snapshots(apps, schema_editor):
        Movement = apps.get_model('inventory', 'StockMovement')
        database = schema_editor.connection.alias
        for movement in Movement.objects.using(database).select_related('actor').iterator():
            if movement.actor_id:
                movement.actor_email_snapshot = movement.actor.email
                movement.save(using=database, update_fields=('actor_email_snapshot',))

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='actor_email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.RunPython(populate_actor_snapshots, migrations.RunPython.noop),
    ]
