# Generated by Django 6.0.8 on 2026-09-27 13:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        ('products', '0002_productcategory_product_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='customers.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='organizations.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='inventory.warehouse')),
            ],
            options={
                'ordering': ('-issued_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=160)),
                ('position', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='products.product')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='PaymentCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank transfer'), ('card', 'Card')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_payment_collections', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_payment_collections', to='organizations.organization')),
            ],
            options={
                'ordering': ('-collected_at', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', '-issued_at'], name='sales_invoice_org_issued_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='unique_sales_invoice_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='sales_invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'position'), name='unique_sales_invoice_line_position'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sales_invoice_line_unit_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='sales_invoice_line_total_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='paymentcollection',
            index=models.Index(fields=['organization', 'invoice', '-collected_at'], name='sales_payment_org_invoice_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentcollection',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='sales_payment_amount_positive'),
        ),
    ]
