# Generated by Django 6.0.8 on 2026-09-28 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_organization_and_more'),
        ('organizations', '0002_alter_membership_role'),
        ('products', '0003_alter_product_category'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_invoices', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_invoices', to='inventory.warehouse'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sales_invoice_lines', to='products.product'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='payments', to='sales.invoice'),
        ),
        migrations.AlterField(
            model_name='paymentcollection',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_payment_collections', to='organizations.organization'),
        ),
    ]
