# Generated by Django 6.0.8 on 2026-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    def populate_actor_snapshots(apps, schema_editor):
        database = schema_editor.connection.alias
        for model_name in ('Invoice', 'PaymentCollection'):
            Model = apps.get_model('sales', model_name)
            for record in Model.objects.using(database).select_related('actor').iterator():
                if record.actor_id:
                    record.actor_email_snapshot = record.actor.email
                    record.save(
                        using=database,
                        update_fields=('actor_email_snapshot',),
                    )

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='actor_email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='paymentcollection',
            name='actor_email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.RunPython(populate_actor_snapshots, migrations.RunPython.noop),
    ]
