# Generated by Django 6.0.8 on 2026-10-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0002_organization_is_active'),
    ]

    def populate_organization_snapshots(apps, schema_editor):
        AuditEvent = apps.get_model('audit', 'AuditEvent')
        database = schema_editor.connection.alias
        for event in AuditEvent.objects.using(database).select_related('organization').iterator():
            if event.organization_id:
                event.organization_id_snapshot = str(event.organization_id)
                event.organization_name_snapshot = event.organization.name
                event.save(
                    using=database,
                    update_fields=(
                        'organization_id_snapshot',
                        'organization_name_snapshot',
                    ),
                )

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='organization_id_snapshot',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='organization_name_snapshot',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.RunPython(populate_organization_snapshots, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='auditevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='organizations.organization'),
        ),
    ]
