# Generated by Django 6.0.8 on 2026-10-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_auditevent_organization_id_snapshot_and_more'),
    ]

    def populate_actor_snapshots(apps, schema_editor):
        AuditEvent = apps.get_model('audit', 'AuditEvent')
        database = schema_editor.connection.alias
        for event in AuditEvent.objects.using(database).select_related('actor').iterator():
            if event.actor_id:
                event.actor_email_snapshot = event.actor.email
                event.save(using=database, update_fields=('actor_email_snapshot',))

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor_email_snapshot',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.RunPython(populate_actor_snapshots, migrations.RunPython.noop),
    ]
